# terme (regex) : (libellé, définition ≤30 mots, URL officielle vérifiée ou None)
G = [
(r"CRA", "Cyber Resilience Act", "Règlement européen 2024/2847 imposant des exigences de cybersécurité aux produits comportant des éléments numériques, avec déclaration des vulnérabilités exploitées depuis le 11 septembre 2026.", "https://eur-lex.europa.eu/eli/reg/2024/2847/oj"),
(r"ANFR", "ANFR", "Agence nationale des fréquences ; désignée par l'ANSSI comme autorité de surveillance des produits numériques mis sur le marché dans le cadre du CRA.", "https://cyber.gouv.fr/actualites/cra-lanssi-lanfr-et-la-dge-accompagnent-les-fabricants-dans-la-conformite-des-produits-numeriques/"),
(r"DGE", "DGE", "Direction générale des entreprises : service du ministère de l'Économie qui accompagne les entreprises, ici pour la mise en conformité au CRA.", None),
(r"CNA", "CNA", "CVE Numbering Authority : organisation autorisée à attribuer des identifiants CVE aux vulnérabilités de son périmètre, sous une racine comme celle de l'ENISA.", "https://www.cve.org/ProgramOrganization/CNAs"),
(r"NCIA", "NCIA", "Agence de communication et d'information de l'OTAN, devenue autorité de numérotation CVE sous la racine ENISA le 6 août 2026.", None),
(r"AISLE", "AISLE", "Entreprise d'IA et de cybersécurité, devenue autorité de numérotation CVE sous la racine ENISA le 6 août 2026.", None),
(r"MITRE", "MITRE", "Organisation à but non lucratif qui exploite historiquement la racine principale du programme CVE.", "https://www.cve.org/"),
(r"OTAN", "OTAN", "Organisation du traité de l'Atlantique Nord : alliance militaire de pays européens et nord-américains.", None),
(r"SSVC", "SSVC", "Stakeholder-Specific Vulnerability Categorization : méthode d'aide à la décision qui classe les vulnérabilités selon leur exploitation et leur impact pour choisir le traitement.", None),
(r"sigstore", "sigstore", "Projet open source de signature et de vérification des artefacts logiciels (versions, images, sommes de contrôle).", "https://www.sigstore.dev/"),
(r"HTML", "HTML", "HyperText Markup Language : langage de description des pages web, aussi utilisé pour des rapports lisibles dans un navigateur.", None),
(r"ENISA", "ENISA", "Agence de l'Union européenne pour la cybersécurité. Elle exploite la plateforme unique de déclaration prévue par le CRA.", "https://www.enisa.europa.eu/"),
(r"CMMC", "CMMC", "Cybersecurity Maturity Model Certification : programme du département américain de la Défense qui impose des niveaux de cybersécurité vérifiés à ses fournisseurs.", "https://dodcio.defense.gov/CMMC/"),
(r"ITAR", "ITAR", "International Traffic in Arms Regulations : réglementation américaine contrôlant l'exportation et la réexportation de matériels de défense, de données techniques et de logiciels associés.", "https://www.ecfr.gov/current/title-22/chapter-I/subchapter-M"),
(r"SAFE", "SAFE", "Security Action for Europe : instrument européen de prêts aux États membres pour l'achat de produits de défense, assorti de règles sur l'origine des composants.", "https://defence-industry-space.ec.europa.eu/creation-security-action-europe-special-group-2025-07-16_en"),
(r"EDIP", "EDIP", "European Defence Industry Programme : programme européen de subventions pour renforcer et moderniser l'industrie de défense, avec règle de composants européens.", "https://defence-industry-space.ec.europa.eu/eu-defence-industry/edip-forging-europes-defence_en"),
(r"NIS2", "NIS2", "Directive européenne fixant des exigences unifiées de cybersécurité et de notification d'incidents pour les entités essentielles et importantes de nombreux secteurs.", "https://digital-strategy.ec.europa.eu/en/policies/nis2-directive"),
(r"DORA", "DORA", "Digital Operational Resilience Act : règlement (UE) 2022/2554 sur la résilience opérationnelle numérique des entités financières.", "https://eur-lex.europa.eu/eli/reg/2022/2554/oj"),
(r"REC", "REC", "Directive sur la résilience des entités critiques : cadre pour que ces entités préviennent, absorbent et surmontent les incidents.", "https://home-affairs.ec.europa.eu/policies/internal-security/counter-terrorism-and-radicalisation/protection/critical-infrastructure-resilience-eu-level_en"),
(r"AI Act", "AI Act", "Règlement européen 2024/1689, premier cadre juridique complet sur l'intelligence artificielle, fondé sur les niveaux de risque.", "https://eur-lex.europa.eu/eli/reg/2024/1689/oj"),
(r"SBOM", "SBOM", "Software Bill of Materials : inventaire structuré des composants d'un logiciel, utilisé pour suivre licences et vulnérabilités.", "https://www.cisa.gov/sbom"),
(r"CISA", "CISA", "Agence américaine de cybersécurité et de sécurité des infrastructures, qui publie notamment les éléments minimaux du SBOM.", "https://www.cisa.gov/"),
(r"CSIRT", "CSIRT", "Équipe nationale de réponse aux incidents de sécurité informatique ; le réseau européen coordonne la réponse aux incidents transfrontaliers.", "https://enisa.europa.eu/topics/eu-cyber-crisis-and-incident-management/csirts-network"),
(r"CJUE", "CJUE", "Cour de justice de l'Union européenne : veille au respect du droit de l'Union par les États membres et les institutions.", "https://curia.europa.eu/"),
(r"OMC", "OMC", "Organisation mondiale du commerce : négocie les accords commerciaux, règle les différends et aide au renforcement des capacités.", "https://www.wto.org/"),
(r"Position commune( 2008/944)?", "Position commune 2008/944/PESC", "Texte du Conseil de l'UE fixant des règles communes pour le contrôle des exportations de technologie et d'équipements militaires.", "https://eur-lex.europa.eu/eli/compos/2008/944/oj"),
(r"traité sur le commerce des armes", "Traité sur le commerce des armes", "Traité international régulant le commerce des armes conventionnelles ; secrétariat à Genève, 118 États parties selon le site officiel.", "https://thearmstradetreaty.org/"),
(r"Omnibus V", "Omnibus V", "Initiative de la Commission pour lever des obstacles et faciliter les investissements de défense, dont la directive sur les transferts intra-UE.", "https://defence-industry-space.ec.europa.eu/eu-defence-industry/defence-readiness-omnibus_en"),
(r"Fonds européen de défense", "Fonds européen de défense", "Mécanisme de financement de l'UE pour la recherche et le développement collaboratifs de défense.", "https://defence-industry-space.ec.europa.eu/eu-defence-industry/european-defence-fund-edf-official-webpage-european-commission_en"),
(r"Eclipse Foundation", "Eclipse Foundation", "Fondation européenne hébergeant plus de 450 projets open source sous gouvernance neutre.", "https://www.eclipse.org"),
(r"OWASP", "OWASP", "Fondation à but non lucratif produisant des projets libres de sécurité applicative (Top 10, ASVS, ZAP) et des ressources éducatives.", "https://owasp.org"),
(r"ORC", "Open Regulatory Compliance WG", "Groupe de travail de la Fondation Eclipse facilitant la collaboration sur la conformité réglementaire, pour préserver l'usage de l'open source dans la chaîne logicielle.", "https://orcwg.org"),
(r"OCCTET", "OCCTET", "Projet financé par l'UE, lancé par la Fondation Eclipse, fournissant des outils libres pour aider PME et communautés open source à se conformer au CRA.", "https://occtet.eu"),
(r"OSS Review Toolkit \(ORT\)", "OSS Review Toolkit", "Boîte à outils en ligne de commande automatisant l'analyse des composants, des licences, des vulnérabilités et l'évaluation de politiques.", "https://oss-review-toolkit.org/ort/"),
(r"OpenSSF", "OpenSSF", "Communauté de développeurs et d'ingénieurs sécurité qui travaillent à sécuriser les logiciels open source.", "https://openssf.org"),
(r"SLSA", "SLSA", "Supply-chain Levels for Software Artifacts : cadre de normes et de contrôles contre la falsification des artefacts logiciels.", "https://slsa.dev"),
(r"CycloneDX", "CycloneDX", "Standard de nomenclature des composants (BOM) pour la chaîne d'approvisionnement, normalisé par Ecma sous la référence ECMA-424.", "https://cyclonedx.org"),
(r"ECMA-424", "ECMA-424", "Norme Ecma International (comité TC54) qui normalise le format CycloneDX.", "https://ecma-international.org/publications-and-standards/standards/ecma-424/"),
(r"SPDX", "SPDX", "System Package Data Exchange : standard ouvert pour décrire les composants logiciels et leurs licences sous forme de SBOM.", "https://spdx.dev"),
(r"Dependency-Track", "OWASP Dependency-Track", "Plateforme open source d'inventaire de composants et de détection de vulnérabilités à partir de SBOM, avec application de politiques.", "https://dependencytrack.org"),
(r"OSV-Scanner", "OSV-Scanner", "Outil de Google qui détecte les vulnérabilités connues des dépendances d'un projet en les rapprochant de la base OSV.", "https://google.github.io/osv-scanner/"),
(r"Anchore", "Anchore", "Éditeur d'une plateforme de sécurité de la chaîne logicielle fondée sur les SBOM : vulnérabilités, gestion des SBOM, conformité.", "https://anchore.com"),
(r"FOSSA", "FOSSA", "Plateforme automatisant la conformité des licences, la sécurité et la gestion des SBOM du code tiers.", "https://fossa.com"),
(r"Snyk", "Snyk", "Plateforme de sécurité qui détecte les vulnérabilités du code, y compris généré par IA.", "https://snyk.io"),
(r"Chainguard", "Chainguard", "Éditeur d'images de conteneurs et de bibliothèques open source sans vulnérabilité connue, conçus pour la sécurité de la chaîne d'approvisionnement.", "https://www.chainguard.dev"),
(r"PyPI", "PyPI", "Python Package Index : dépôt officiel où l'on trouve, installe et partage les paquets du langage Python.", "https://pypi.org"),
(r"GitHub", "GitHub", "Plateforme collaborative de développement logiciel : gestion de versions, sécurité et déploiement intégrés.", "https://github.com"),
(r"npm", "npm", "Gestionnaire de paquets de Node.js et registre où se publient les modules JavaScript.", "https://www.npmjs.com"),
(r"SFC", "Software Freedom Conservancy", "Organisation à but non lucratif qui héberge des projets de logiciels libres et défend les droits liés à la liberté logicielle.", "https://sfconservancy.org"),
(r"OSI", "Open Source Initiative", "Association à but non lucratif, gardienne de l'Open Source Definition qui établit les standards de l'open source.", "https://opensource.org"),
(r"BIS", "BIS", "Bureau of Industry and Security : service du département américain du Commerce chargé du contrôle des exportations.", "https://www.bis.gov"),
(r"EAR", "EAR", "Export Administration Regulations : règles américaines de contrôle des exportations, avec classification ECCN et restrictions par pays.", "https://www.bis.gov/regulations/ear"),
(r"OFAC", "OFAC", "Office of Foreign Assets Control : service du Trésor américain qui administre et fait appliquer les sanctions économiques.", "https://ofac.treasury.gov"),
(r"DDTC", "DDTC", "Directorate of Defense Trade Controls : service du département d'État américain chargé du contrôle des exportations de matériels de défense.", "https://www.pmddtc.state.gov"),
(r"DGA", "DGA", "Direction générale de l'armement du ministère des Armées : expertise, essais, ingénierie et partenariats industriels pour l'armement.", "https://www.defense.gouv.fr/dga"),
(r"CIEEMG", "CIEEMG", "Commission interministérielle pour l'étude des exportations de matériels de guerre, présidée par le SGDSN, qui instruit les demandes d'exportation.", "https://www.sgdsn.gouv.fr/nos-missions/anticiper-et-prevenir/controler-les-exportations-de-materiels-de-guerre"),
(r"SIGALE", "SIGALE", "Téléservice de la DGA pour déposer les demandes de licences individuelles d'exportation de matériels de guerre.", "https://armement.defense.gouv.fr/international/sigale/depot-des-licences"),
(r"ANSSI", "ANSSI", "Agence nationale de la sécurité des systèmes d'information : défend, informe, accompagne et régule ; héberge le CERT-FR.", "https://cyber.gouv.fr"),
(r"SecNumCloud", "SecNumCloud", "Qualification de l'ANSSI des offres cloud de confiance, fondée sur un référentiel d'exigences.", "https://cyber.gouv.fr/enjeux-technologiques/cloud/"),
(r"règlement 2021/821", "Règlement (UE) 2021/821", "Règlement instituant le régime de l'Union de contrôle des exportations, du courtage, de l'assistance technique, du transit et des transferts de biens à double usage.", "https://eur-lex.europa.eu/eli/reg/2021/821/oj"),
(r"directive \(UE\) 2024/2853", "Directive (UE) 2024/2853", "Directive sur la responsabilité du fait des produits défectueux ; remplace la directive 85/374/CEE et inclut le logiciel.", "https://eur-lex.europa.eu/eli/dir/2024/2853/oj"),
# sans lien officiel vérifié
(r"Grype", "Grype", "Scanneur open source de vulnérabilités pour images de conteneurs et systèmes de fichiers, souvent utilisé avec des SBOM.", None),
(r"EUCC", "EUCC", "Schéma européen de certification de cybersécurité fondé sur les Critères communs ; sa présomption de conformité au CRA est attendue.", None),
(r"DFARS 252\.204-7012", "DFARS 252.204-7012", "Clause du règlement d'acquisition de la Défense américaine imposant la protection des informations non classifiées et la déclaration des incidents cyber.", None),
(r"CMCAP", "CMCAP", "Contrôle a posteriori des exportations de matériels de guerre, exercé après la délivrance des licences.", None),
(r"ReCyF", "ReCyF", "Référentiel de cybersécurité publié par l'ANSSI le 17 mars 2026, cité dans le cadre de la transposition de la directive NIS2.", None),
(r"OpenChain", "OpenChain", "Projet de la Linux Foundation qui définit une norme de gestion de la conformité des licences open source.", None),
(r"Honeywell", "Honeywell", "Industriel américain de l'aérospatiale, de l'automatisation et des technologies de défense.", None),
(r"Safran", "Safran", "Groupe industriel français d'aéronautique, d'espace et de défense.", None),
(r"MBDA", "MBDA", "Missilier européen, spécialisé dans les systèmes de missiles.", None),
(r"Vizio", "Vizio", "Fabricant américain de téléviseurs connectés, visé par la procédure de la Software Freedom Conservancy sur la licence GPL.", None),
(r"AGPL", "AGPL", "GNU Affero General Public License : licence copyleft étendant ses obligations aux logiciels utilisés via un réseau.", None),
(r"SSPL", "SSPL", "Server Side Public License : licence non approuvée par l'OSI, imposant la publication du code des services offerts autour du logiciel.", None),
(r"BSL", "BSL", "Business Source License : licence à code source disponible qui restreint l'usage commercial pendant une période avant ouverture.", None),
(r"TanStack", "TanStack", "Ensemble de bibliothèques JavaScript open source, dont des paquets npm très utilisés ; compromis en mai 2026 dans une attaque de la chaîne d'approvisionnement.", None),
(r"Jscrambler", "Jscrambler", "Éditeur de solutions de protection du code JavaScript, dont un jeton de publication a été volé en juillet 2026.", None),
(r"AsyncAPI", "AsyncAPI", "Projet open source de spécification et d'outils pour décrire des API asynchrones ; son pipeline d'intégration continue a été détourné en juillet 2026.", None),
(r"Dependabot", "Dependabot", "Outil de GitHub qui propose automatiquement des mises à jour de dépendances et alerte sur les vulnérabilités.", "https://docs.github.com/en/code-security/dependabot"),
(r"OFSI", "OFSI", "Office of Financial Sanctions Implementation : autorité britannique chargée de la mise en œuvre des sanctions financières.", "https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation"),
(r"Mistral AI", "Mistral AI", "Entreprise française d'intelligence artificielle qui publie des SDK sur npm et PyPI.", None),
(r"Golden Global Bank", "Golden Global Bank", "Banque turque visée par l'OFAC le 4 septembre 2026 pour des transactions liées aux Gardiens de la révolution iraniens.", None),
(r"FossID", "FossID", "Éditeur d'outils d'analyse de composition logicielle (Software Composition Analysis) identifiant le code open source et ses licences.", None),
(r"Unleash", "Unleash", "Plateforme open source de gestion de fonctionnalités (feature flags), passée à la licence AGPLv3 en 2026.", None),
(r"VEX", "VEX", "Vulnerability Exploitability eXchange : document indiquant si un produit est réellement affecté par une vulnérabilité connue d'un composant.", None),
(r"Open Source Summit Europe", "Open Source Summit Europe", "Conférence européenne de la Linux Foundation consacrée à l'open source.", None),
(r"Farnborough", "Salon de Farnborough", "Salon aéronautique et de défense organisé au Royaume-Uni.", None),
(r"CVE", "CVE", "Common Vulnerabilities and Exposures : programme qui attribue un identifiant unique à chaque vulnérabilité publiquement connue.", "https://www.cve.org/"),
(r"NVD", "NVD", "National Vulnerability Database : base américaine du NIST qui enrichit les CVE (gravité, produits concernés).", "https://nvd.nist.gov/"),
(r"OSV", "OSV", "Open Source Vulnerabilities : base de données et format ouverts recensant les vulnérabilités des paquets open source.", "https://osv.dev/"),
(r"GPL", "GPL", "GNU General Public License : licence libre copyleft qui impose de fournir le code source des œuvres dérivées distribuées.", "https://www.gnu.org/licenses/"),
(r"ISO(/IEC)?", "ISO/IEC", "Organisation internationale de normalisation et Commission électrotechnique internationale, qui publient conjointement les normes des technologies de l'information.", "https://www.iso.org/"),
(r"JO", "Journal officiel de l'UE", "Publication officielle des actes de l'Union européenne ; leur entrée en vigueur dépend de cette publication.", "https://eur-lex.europa.eu/"),
(r"EEE-AELE", "EEE-AELE", "États de l'Association européenne de libre-échange membres de l'Espace économique européen (Islande, Liechtenstein, Norvège), associés au marché intérieur.", "https://www.efta.int/"),
(r"DIGITALEUROPE", "DIGITALEUROPE", "Association professionnelle représentant l'industrie numérique en Europe auprès des institutions de l'UE.", "https://www.digitaleurope.org/"),
(r"RGPD", "RGPD", "Règlement général sur la protection des données, règlement (UE) 2016/679.", "https://eur-lex.europa.eu/eli/reg/2016/679/oj"),
(r"THUNDART", "THUNDART", "Système de frappe terrestre longue portée de Safran et MBDA, présenté comme ITAR-free.", "https://www.safran-group.com/products-services/thundart-long-range-land-strike-system"),
(r"SREN", "Loi SREN", "Loi française n° 2024-449 du 21 mai 2024 visant à sécuriser et à réguler l'espace numérique.", None),
(r"ETSI", "ETSI", "Institut européen des normes de télécommunications : organisme européen de normalisation, chargé avec le CEN et le CENELEC des normes harmonisées du CRA.", "https://www.etsi.org/"),
(r"EN", "Norme européenne (EN)", "Norme adoptée par un organisme européen de normalisation (CEN, CENELEC ou ETSI) ; une norme harmonisée citée au JO donne présomption de conformité.", "https://single-market-economy.ec.europa.eu/single-market/european-standards_en"),
(r"IBM", "IBM", "Entreprise informatique américaine, membre fondateur de nombreuses fondations open source.", None),
(r"FBI", "FBI", "Police fédérale américaine ; coauteur, avec la CISA et la NSA, des éléments minimaux du SBOM 2026.", None),
(r"NSA", "NSA", "Agence américaine du renseignement d'origine électromagnétique et de la cybersécurité ; coautrice des éléments minimaux du SBOM 2026.", None),
(r"NTIA", "NTIA", "Administration américaine des télécommunications et de l'information, qui avait publié en 2021 les premiers éléments minimaux du SBOM.", None),
(r"SDK", "SDK", "Software Development Kit : trousse d'outils et de bibliothèques fournie par un éditeur pour développer des logiciels qui utilisent son service.", None),
(r"UTC", "UTC", "Temps universel coordonné : référence horaire internationale, décalée de une ou deux heures par rapport à l'heure de Paris.", None),
(r"CBOM", "CBOM", "Cryptographic Bill of Materials : inventaire des fonctions cryptographiques (algorithmes, clés, protocoles) d'un matériel ou d'un logiciel.", None),
(r"EAR99", "EAR99", "Catégorie de l'EAR pour les biens soumis à la réglementation américaine mais absents de la liste de contrôle ; licence requise seulement pour certaines destinations ou utilisateurs.", "https://www.bis.gov/"),
(r"ECCN", "ECCN", "Export Control Classification Number : numéro de classement d'un bien, logiciel ou technologie dans la liste de contrôle américaine (EAR).", "https://www.bis.gov/"),
(r"HTS", "HTS", "Harmonized Tariff Schedule : nomenclature douanière des États-Unis, utilisée pour les droits de douane à l'importation.", None),
(r"NIST SP 800-171", "NIST SP 800-171", "Publication du NIST qui fixe les exigences de sécurité pour protéger les informations non classifiées contrôlées chez les fournisseurs du gouvernement américain.", None),
(r"NIST", "NIST", "Institut national américain des normes et de la technologie ; il publie notamment les normes FIPS et gère la base NVD.", "https://www.nist.gov/"),
(r"QAD", "QAD", "Éditeur américain de logiciels de gestion industrielle.", None),
(r"SCA", "SCA", "Software Composition Analysis : analyse des composants tiers d'un logiciel (inventaire, vulnérabilités, licences).", None),
(r"SOC 2(?: Type II)?", "SOC 2", "Rapport d'audit américain sur les contrôles de sécurité d'un prestataire de services ; le Type II teste leur fonctionnement sur une période.", None),
]
